NC_READ_REQUEST     = 0
NC_READ_REPLY       = 1
NC_HOT_READ_REQUEST = 2
NC_WRITE_REQUEST    = 4
NC_WRITE_REPLY      = 5
NC_UPDATE_REQUEST   = 8
NC_UPDATE_REPLY     = 9


NC_PORT = 8888
CLIENT_IP = "10.0.0.1"
SERVER_IP = "10.0.0.2"
CONTROLLER_IP = "10.0.0.3"

KEY_SIZE = 16 # bytes
VALUE_SIZE = 16 # bytes
